version: '3.9'

services:
  postgres_faunatrack:
    image: postgres:14-alpine
    restart: always
    container_name: postgres_faunatrack
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    expose:
      - 5432
    networks:
      - backend

  django:
    build: .
    restart: always
    container_name: django
    env_file:
      - ./.env
    volumes:
      - static_volume:/pythagore/static
    depends_on:
      - postgres_faunatrack
    expose:
      - 8000
    networks:
      - backend

  nginx_faunatrack:
    image: nginx:alpine
    restart: always
    container_name: nginx_faunatrack
    volumes:
      - static_volume:/app/static
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
    ports:
      - 80:80
      - 443:443
    networks:
      - backend

volumes:
  postgres_db_data:
    name: postgres_db_data
  static_volume:

networks:
  backend: